DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Votes;

CREATE TABLE Users (
    username VARCHAR PRIMARY KEY,
    passw VARCHAR,
    dataRegistered DATE
);

CREATE TABLE Posts
(
    postID INTEGER UNIQUE NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL,
    content VARCHAR,
    link VARCHAR,
    image VARCHAR,
    dateWritten DATETIME,
    username INTEGER REFERENCES Users Not NULL
);

CREATE TABLE Comments
(
    commentID INTEGER UNIQUE NOT NULL PRIMARY KEY,
    content TEXT,
    dateWritten DATETIME NOT NULL,
    postID INTEGER REFERENCES Posts Not NULL
);

CREATE TABLE Votes
(
    commentID INTEGER NOT NULL REFERENCES Comments,
    username VARCHAR NOT NULL REFERENCES Users,
    positive INTEGER,
    PRIMARY KEY(commentID,username)
);

INSERT INTO Users VALUES ('Andre','12345',NULL);
INSERT INTO Users VALUES ('Joao','234','2018-06-20');
INSERT INTO Users VALUES ('Andre1','12345',NULL);

INSERT INTO Posts VALUES (1,'SOMESADS','COTNESRTE',NULL,NULL,NULL,'Andre');
INSERT INTO Posts VALUES (2,'SOSADAMESADS','COTNESRTE',NULL,NULL,NULL,'Andre');

INSERT INTO Votes VALUES (1,'Joao',1);
INSERT INTO Votes Values (1,'Andre',0);
INSERT INTO Votes VALUES (2,'Joao',1);

SELECT * FROM Users;
SELECT Count(*) FROM Votes WHERE (positive = 1 AND commentID=1);
